### ISSUE TITLE
Black stripes around the screen

### ISSUE THREAD

**Issue by Bulb1k1** [wesley-prado/wallpaper-wavygrass-clock#1]
Hi there! I have a problem after the last update. I have black stripes around the perimeter of the screen. I use a 2k monitor 2560x1440.
![image](https://github.com/wesley-prado/wallpaper-wavygrass-clock/assets/141710285/623751b1-965d-4475-aab9-b6f02f7d07da)

**Comment by wesley-prado** [comment]
Hello, @Bulb1k1. How are you doing? I hope you're doing well.
Your problem seems that you have a screen larger than the video background. Try changing the Background Alignment from “Center” to “Cover” by enabling the “Advanced properties”. Now, you can also change the background to another video or image that better fits your taste and screen size.

I'll change the default alignment to “Cover” in the next patch. Thanks for your contact and let me know if I helped you. 😁

**Comment by Bulb1k1** [comment]
Thanks! That worked!
